In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.preprocessing import FunctionTransformer
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.datasets import make_classification
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import classification_report
from sklearn.compose import ColumnTransformer
df = pd.DataFrame({"col1":[-0.73,-2.36, 2.17, np.nan, -0.82, "1.83",  1.66, np.nan,  0.78 , 1.56, 2.82, 3.55],
                   "col2":[ 0.21, -0.089 , -1.34,  2.57,  1.81, -1.77, -0.28, -0.73, -0.99, -1.54, 0.45, -0.67],
                   "col3":[-0.92, np.nan,  1.92 , -1.42 , -0.38, 1.47,  np.nan, -1.79,  np.nan,  1.22, 0.56, -0.34],
                   "cat":["B", "B", "M", "B", "B", "M", np.nan, "B", "M", "M", "B", "M"],
                   "peso":[80, 70, 50, 60, 90, 55, 65, 85, 75, 45, 68, 72],
                   "altura":[1.80, 1.75, 1.60, 1.70, 1.85, 1.65, 1.68, 1.82, 1.78, 1.55, 1.72, 1.74],
                   "target":[0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1]})

Funciones para ajustar tipos erroneos y calculo de IMC

In [186]:

def type_normalizer(X):
    X = X.copy()
    X["col1"] = X["col1"].astype(float)
    return X

In [187]:
df

    col1   col2  col3  cat  peso  altura  target
0  -0.73  0.210 -0.92    B    80    1.80       0
1  -2.36 -0.089   NaN    B    70    1.75       0
2   2.17 -1.340  1.92    M    50    1.60       1
3    NaN  2.570 -1.42    B    60    1.70       0
4  -0.82  1.810 -0.38    B    90    1.85       0
5   1.83 -1.770  1.47    M    55    1.65       1
6   1.66 -0.280   NaN  NaN    65    1.68       1
7    NaN -0.730 -1.79    B    85    1.82       0
8   0.78 -0.990   NaN    M    75    1.78       1
9   1.56 -1.540  1.22    M    45    1.55       1
10  2.82  0.450  0.56    B    68    1.72       0
11  3.55 -0.670 -0.34    M    72    1.74       1

In [188]:
#sns.pairplot(df[["col1", "col2", "col3", "target"]], hue='target')
X = df.drop("target", axis=1)
y = df["target"]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=3, test_size=0.3)

In [189]:

ct0 = ColumnTransformer([("dtype", FunctionTransformer(type_normalizer, validate=False), ["col1"])],
                         remainder="passthrough",
                         force_int_remainder_cols=False,
                         verbose_feature_names_out=False)

ct1 = ColumnTransformer([("mean_col1", SimpleImputer(strategy="mean"), ["col1"]),
                        ("median_col3", SimpleImputer(strategy="median") , ["col3"]),
                        ("most_freq_cat", SimpleImputer(strategy="most_frequent") , ["cat"])
                        ], remainder='passthrough', force_int_remainder_cols=False, verbose_feature_names_out=False)
ct2 = ColumnTransformer([("OneHot", OneHotEncoder(sparse_output=False, dtype=int, drop='first') , ["cat"])],
                         remainder='passthrough', 
                         force_int_remainder_cols=False,
                         verbose_feature_names_out=False)

ct_list = [ct0, ct1, ct2]
for ct in ct_list:
    ct.set_output(transform="pandas")

In [190]:
ct0.fit_transform(X_train).dtypes

col1      float64
col2      float64
col3      float64
cat        object
peso        int64
altura    float64
dtype: object

In [191]:
pl = Pipeline(steps=[("ct0", ct0),
                     ("ct1", ct1),
                     ("ct2", ct2),
                     ("est", KNeighborsClassifier())])

In [192]:
pl

Pipeline(steps=[('ct0',
                 ColumnTransformer(force_int_remainder_cols=False,
                                   remainder='passthrough',
                                   transformers=[('dtype',
                                                  FunctionTransformer(func=<function type_normalizer at 0x000001AD400349D0>),
                                                  ['col1'])],
                                   verbose_feature_names_out=False)),
                ('ct1',
                 ColumnTransformer(force_int_remainder_cols=False,
                                   remainder='passthrough',
                                   transformers=[('mean_col1', SimpleI...
                                                  ['col3']),
                                                 ('most_freq_cat',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  ['cat'])],
                                   verbose_feature_names_out=False)),
                ('ct2',
                 ColumnTransformer(force_int_remainder_cols=False,
                                   remainder='passthrough',
                                   transformers=[('OneHot',
                                                  OneHotEncoder(drop='first',
                                                                dtype=<class 'int'>,
                                                                sparse_output=False),
                                                  ['cat'])],
                                   verbose_feature_names_out=False)),
                ('est', KNeighborsClassifier())])

In [193]:
pl[:-1].fit_transform(X_train)

    cat_M      col1  col3  col2  peso  altura
11      1  3.550000 -0.34 -0.67    72    1.74
6       0  1.660000 -0.63 -0.28    65    1.68
7       0  1.606667 -1.79 -0.73    85    1.82
0       0 -0.730000 -0.92  0.21    80    1.80
3       0  1.606667 -1.42  2.57    60    1.70
9       1  1.560000  1.22 -1.54    45    1.55
8       1  0.780000 -0.63 -0.99    75    1.78
10      0  2.820000  0.56  0.45    68    1.72

Es importante ver que por paralelización todas las operaciones se hacen de manera concurrente, si quiero primero imputar la categorica y luego transformarla en numérica necesito otro ct

In [194]:
pl = Pipeline(steps=[
    ("ct0", ct0),
    ("ct1", ct1),
    ("ct2", ct2),
    ("est", KNeighborsClassifier())])

In [195]:
pl

Pipeline(steps=[('ct0',
                 ColumnTransformer(force_int_remainder_cols=False,
                                   remainder='passthrough',
                                   transformers=[('dtype',
                                                  FunctionTransformer(func=<function type_normalizer at 0x000001AD400349D0>),
                                                  ['col1'])],
                                   verbose_feature_names_out=False)),
                ('ct1',
                 ColumnTransformer(force_int_remainder_cols=False,
                                   remainder='passthrough',
                                   transformers=[('mean_col1', SimpleI...
                                                  ['col3']),
                                                 ('most_freq_cat',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  ['cat'])],
                                   verbose_feature_names_out=False)),
                ('ct2',
                 ColumnTransformer(force_int_remainder_cols=False,
                                   remainder='passthrough',
                                   transformers=[('OneHot',
                                                  OneHotEncoder(drop='first',
                                                                dtype=<class 'int'>,
                                                                sparse_output=False),
                                                  ['cat'])],
                                   verbose_feature_names_out=False)),
                ('est', KNeighborsClassifier())])

In [196]:

temp = pl[:-1].fit_transform(X_train)
temp

    cat_M      col1  col3  col2  peso  altura
11      1  3.550000 -0.34 -0.67    72    1.74
6       0  1.660000 -0.63 -0.28    65    1.68
7       0  1.606667 -1.79 -0.73    85    1.82
0       0 -0.730000 -0.92  0.21    80    1.80
3       0  1.606667 -1.42  2.57    60    1.70
9       1  1.560000  1.22 -1.54    45    1.55
8       1  0.780000 -0.63 -0.99    75    1.78
10      0  2.820000  0.56  0.45    68    1.72

In [197]:
pl.fit(X_train, y_train)
y_pred = pl.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.67      1.00      0.80         2

    accuracy                           0.75         4
   macro avg       0.83      0.75      0.73         4
weighted avg       0.83      0.75      0.73         4

¿Me olvide de alguna transformación? Sin contar el IMC, eso lo dejamos para mas adelante